use std::io::prelude::*;
use std::fs::File;
use std::path::{Path, PathBuf};
use std::collections::HashMap;

use core::engine_support_systems::system_management::system_types::{VSystem, SystemType};
use core::engine_support_systems::system_management::loggers::VLog;
use core::engine_support_systems::error_handling::error::{GameResult, GameError};

//TODO: Rewrite Logger completely

//The logger create 2 files on start_up() : the general log file, and the logger dedicated log file.
//The logger check that the filesystem structure has been generated by the Workspace subsystem.
#[derive(Debug)]
pub struct Logger {

}

impl Logger {

}

impl VSystem for Logger {

    fn shut_down(&mut self) -> GameResult<()> {
        //TODO: finish this func
        Ok(())
    }

    fn system_type(&self) -> SystemType {
        SystemType::Log
    }
}

impl VLog for Logger {
    fn write_to_dedicated_log(&mut self, system_type: SystemType, message: &str) -> GameResult<()> {
        /*
        match system_type {
            SystemType::Physic => {
                match self.files.get_mut(&SystemType::Physic) {
                    Some(file) => match file.write_all(message.as_bytes()) {
                        Ok(()) => Ok(()),
                        Err(e) => Err(GameError::LogError(format!("Error while writing in the '{}' log !", system_type),Some(e))),
                    },
                    None => Err(GameError::LogError(format!("The '{}' log could not be found !", system_type), None)),
                }
            },
            SystemType::Input => {
                match self.files.get_mut(&SystemType::Input) {
                    Some(file) => match file.write_all(message.as_bytes()) {
                        Ok(()) => Ok(()),
                        Err(e) => Err(GameError::LogError(format!("Error while writing in the '{}' log !", system_type), Some(e))),
                    },
                    None => Err(GameError::LogError(format!("The '{}' log could not be found !", system_type), None)),
                }
            },
            SystemType::Resource => {
                match self.files.get_mut(&SystemType::Resource) {
                    Some(file) => match file.write_all(message.as_bytes()) {
                        Ok(()) => Ok(()),
                        Err(e) => Err(GameError::LogError(format!("Error while writing in the '{}' log !", system_type), Some(e))),
                    },
                    None => Err(GameError::LogError(format!("The '{}' log could not be found !", system_type), None)),
                }
            },
            SystemType::Rendering => {
                match self.files.get_mut(&SystemType::Rendering) {
                    Some(file) => match file.write_all(message.as_bytes()) {
                        Ok(()) => Ok(()),
                        Err(e) => Err(GameError::LogError(format!("Error while writing in the '{}' log !", system_type), Some(e))),
                    },
                    None => Err(GameError::LogError(format!("The '{}' log could not be found !", system_type), None)),
                }
            },
            SystemType::Log => {
                match self.files.get_mut(&SystemType::Log) {
                    Some(file) => match file.write_all(message.as_bytes()) {
                        Ok(()) => Ok(()),
                        Err(e) => Err(GameError::LogError(format!("Error while writing in the '{}' log !", system_type), Some(e))),
                    },
                    None => Err(GameError::LogError(format!("The '{}' log could not be found !", system_type), None)),
                }
            },
            SystemType::Audio => {
                match self.files.get_mut(&SystemType::Audio) {
                    Some(file) => match file.write_all(message.as_bytes()) {
                        Ok(()) => Ok(()),
                        Err(e) => Err(GameError::LogError(format!("Error while writing in the '{}' log !", system_type), Some(e))),
                    },
                    None => Err(GameError::LogError(format!("The '{}' log could not be found !", system_type), None)),
                }
            },
        }
        */
        Ok(())
    }
}